# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b4dbaeaac3eb77fa65c892e2009efbb92d9f53fe1884d127f2da79f145fe144d3d7702fc583262a474bc3cf7b3af854d7310e475dba9a10ce9e9faf4141507ff

test:
  secret_key_base: 4402c81ecbacf89cd513e170d41335e56d0ee37fecdb89d315e443d5b9f5ee2bf2e7c4b7eba32100ca932276596734123d9a82869d7bb55370c7ad6aa93c1d6c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
